// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'const.dart' show macAPI, androidAPI, iosAPI;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: androidAPI,
    appId: '1:883720375137:android:6d62847bbe1489f8531320',
    messagingSenderId: '883720375137',
    projectId: 'arxorts',
    storageBucket: 'arxorts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: iosAPI,
    appId: '1:883720375137:ios:1bb711fbc7318fd4531320',
    messagingSenderId: '883720375137',
    projectId: 'arxorts',
    storageBucket: 'arxorts.firebasestorage.app',
    iosBundleId: 'com.example.arxorts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: macAPI,
    appId: '1:883720375137:ios:1bb711fbc7318fd4531320',
    messagingSenderId: '883720375137',
    projectId: 'arxorts',
    storageBucket: 'arxorts.firebasestorage.app',
    iosBundleId: 'com.example.arxorts',
  );
}
